### PR TITLE
Feature/Integrate Jasper Reports & Optimize Libraries List

### PR DESCRIPTION
**Pull request by rizkyfazarul**

### CODE REVIEW

**Comment by husainazkas** [comment]
kasih deskripsi ky @rizkyfazarul ada lib apa aja yg perlu di install utk ngetes PR ini

**Review by sekayrim — APPROVED** [review]

**Comment by sekayrim** [comment]
> kasih deskripsi ky @rizkyfazarul ada lib apa aja yg perlu di install utk ngetes PR ini, soale ane mau nge resolve conflict merge ini kena error di library not found. kek si jasper report nya gitu gitu

Keknya maren cuma nambahin lib yg dri share wa itu sen. ya ga? @rizkyfazarul

**Comment by rizkyfazarul** [comment]
Sort and register libraries:
Jasper Report
then put in Jasper Report
commons-beanutils-1.8.2.jar
commons-collections-3.2.1.jar
commons-digester-2.1.jar
commons-logging-1.1jar
groovy-all-2.0.1.jar
jasperreports-5.6.0.jar
org-jdesktop-layout.jar

don't forget to install pulgins
heve a great day

**Review by husainazkas — APPROVED** [review]
dahlah mantap

**Pull request merged**
